#!/usr/bin/env bash

set -eo pipefail

if bw login --check; then
    lg "Already logged in"
    exit 0
elif [ -z "$BWEMAIL" ]; then
    lg "BWEMAIL is not set"
    exit 1
else
    bw login "$BWEMAIL"
fi
