#!/usr/bin/env bash

set -eo pipefail

if rbw unlocked; then
    echo "Rbw is already setup, lock rbw first to switch to another account"
    exit 0
elif [ -z "$RBWEMAIL" ]; then
    echo "RBWEMAIL is not set"
    exit 1
fi

lg "Setting up bitwarden cli."
# Always use my personal bitwarden account as this also contains a work section
rbw config set email "$RBWEMAIL"
rbw config set lock_timeout 86400
lg "Finished setting up bitwarden."
