#!/usr/bin/env zsh

set -eo pipefail

if rbw unlocked; then
    echo "Rbw is already setup, lock rbw first to switch to another account"
    exit 0
fi

lg "Setting up bitwarden cli."
# Always use my personal bitwarden account as this also contains a work section
rbw config set email "$(bw-cli-get username MicrosoftPersonal)"
rbw config set lock_timeout 86400
rbw login
rbw sync
lg "Finished setting up bitwarden."
