#!/bin/bash
#

if rbw unlocked; then
    echo "Rbw is already setup, lock rbw first to switch to another account"
    exit 0
fi 

lg "Setting up bitwarden cli."
lg "Which bitwarden email to use? Enter below:"
read email
rbw config set email $email
rbw config set lock_timeout 86400
rbw login
rbw sync
lg "Finished setting up bitwarden."
