#!/usr/bin/env bash

set -eo pipefail

if [ -z "$BWEMAIL" ]; then
    lg "BWEMAIL is not set (skipping rbw config)"
    exit 0
fi

lg "Setting up bitwarden cli (non-interactive)."
# Always use my personal bitwarden account as this also contains a work section
rbw config set email "$BWEMAIL"
rbw config set lock_timeout 86400
