#!/usr/bin/env bash

set -eo pipefail

if rbw unlocked; then
    lg "Rbw is already setup."
    exit 0
elif [ -z "$BWEMAIL" ]; then
    lg "BWEMAIL is not set"
    exit 1
fi

lg "Setting up bitwarden cli."
# Always use my personal bitwarden account as this also contains a work section
rbw config set email "$BWEMAIL"
rbw config set lock_timeout 86400

lg "Logging into bitwarden."
rbw login
rbw sync
