#!/usr/bin/env bash

usage="Usage: $(basename "$0") [-h|--help] [URL]

This script updates the /etc/hosts file with the contents of the specified URL 
as a positional argument. 

Arguments:
    URL    The URL to download the hosts file from.

Options:
    -h, --help    Show this help message and exit."

while [[ $# -gt 0 ]]; do
    case $1 in
    -h | --help)
        echo "$usage"
        exit 0
        ;;
    *)
        readonly hostsource=$1
        shift
        ;;
    esac
done

readonly tmpfile=/tmp/hosts
readonly hostsfile=/etc/hosts

if ! [[ -w $hostsfile ]]; then
    echo "Can't write to $hostsfile. Check your permissions."
    exit 1
fi

rm -- "$tmpfile" 2>/dev/null

if ! curl --max-time 60 -sL --fail "$hostsource" -o "$tmpfile"; then
    echo "Couldn't download from $hostsource to $tmpfile. Check your internet connection."
    exit 1
fi

{
    echo "# NOTE: Written by $0 on $(date '+%c')"
    cat -- "$tmpfile"
} >"$hostsfile"

echo "$hostsfile has been updated successfully."

rm -- "$tmpfile"
