#!/usr/bin/env bash

usage="Usage: $(basename "$0") <ipset> <file>

Restore the <ipset> from the <file>. If the ipset already exists, do nothing.

options:
  -h, --help  Show this help message and exit"

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "$usage"
    exit 0
fi

if [[ "$#" -ne 2 ]]; then
    echo "$usage"
    exit 1
fi

ipset=$1
file=$2

if ! ipset create "$ipset" hash:ip &>/dev/null; then
    echo "ipset $ipset already exists"
    exit 0
fi

echo "Restoring ipset $ipset from $file"
ipset restore <"$file"
