#!/usr/bin/env bash

this_dir=$(readlink -f "$(dirname "$0")")

URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts"
IPSET="blocked"

echo "Installing the 'ipset-load' command"
sudo cp -f "$this_dir/ipset-load" /usr/local/bin/ipset-load

echo "Downloading blocklist from $URL and saving in ipset format to /etc/ipset.conf with name $IPSET"
dnscacher -o ipset -i "$IPSET" update "$URL" | sudo tee /etc/ipset.conf &>/dev/null

sudo ipset-load "$IPSET" /etc/ipset.conf

if ! sudo iptables -C INPUT -m set --match-set "$IPSET" src -j DROP &>/dev/null; then
    echo "Adding iptables rule to drop packets from ipset $IPSET"
    sudo iptables -I INPUT -m set --match-set "$IPSET" src -j DROP
else
    echo "iptables rule to drop packets from ipset $IPSET already exists"
fi

echo "Saving iptables rules to /etc/iptables/iptables.rules"
sudo iptables-save | sudo tee /etc/iptables/iptables.rules &>/dev/null

# TODO: start ipset-load.service
