#!/usr/bin/env bash
set -euo pipefail
this_dir=$(dirname "$(readlink -f "$0")")

. "$this_dir"/conditions.bash
. "$this_dir"/openers.bash
. "$this_dir"/logger.bash

usage="Usage: $0 <path>
Opens a path in a preferred program.

The option -w, --win can be used to convert all windows paths to wsl paths. 
This is useful when you want to open a windows file in wsl. All arguments
after the options will be interpreted as a path that should be opened, though 
-- can also be used to indicate the end of the options.

Options:
    -h, --help      Show this message and exit.
    -w, --win       Convert windows paths to wsl paths, by default this is not
                    done. If wsl is not running, this fails and is ignored.
    -l, --log       Send debug messages a file.
    -q, --quiet     Suppress all output.
    -v, --verbose   Show more output."

path=""
win=""
while [[ $# -gt 0 ]]; do
    case $1 in
    -h | --help)
        echo "$usage"
        exit 0
        ;;
    -w | --win)
        win="-w"
        ;;
    -l | --log)
        OPEN_LOG_FILE="$2"
        shift
        ;;
    -q | --quiet)
        OPEN_LOG_LEVEL="quiet"
        ;;
    -v | --verbose)
        OPEN_LOG_LEVEL="verbose"
        ;;
    --)
        shift
        break
        ;;
    *)
        if [[ -z $path ]]; then
            path=$1
        else
            echo "Unknown option: $1" >&2
            exit 1
        fi
        ;;
    esac
    shift
done

log "Opening path/url: $path" -v
log "Options: win is: $win" -v

if is_url "$path"; then
    open_url "$path"

elif is_html "$path"; then
    open_url "$path"

elif is_image "$path"; then
    open_img "$path"

elif is_pdf "$path"; then
    zathura "$path"

elif is_text "$path"; then
    open_text "$path" "$win"

elif running_tmux; then
    tmux display-message -d 2000 "No handler for $path."

else
    echo "No handler for $path."
fi
