#!/usr/bin/env bash

unlock() {
    [[ -z "$git_dir" ]] && {
        echo "git_dir is empty"
        exit 1
    }
    [[ -z "$work_tree" ]] && {
        echo "work_tree is empty"
        exit 1
    }
    rbw get base | base64 -d | git --git-dir=$git_dir --work-tree=$work_tree crypt unlock - 
}

git_dir=$WH/dotfiles.git
work_tree=$WH

echo "Unlocking git crypt on repo dotfiles on windows"
echo "git-dir: $git_dir"
echo "work-tree: $work_tree"

running_wsl || { echo "Not running on WSL" && exit 1; }
unlock || { echo "Failed to unlock git crypt" && exit 1; }
echo "Successfully unlocked git crypt"
