#!/usr/bin/env bash

. ~/dotfiles-linux/zsh/git.zsh

echo "Unlocking git crypt on repo dotfiles"

unlock() {
    rbw get base | base64 -d | base crypt unlock -
}

unlock && echo "git crypt unlocked" || echo "git crypt unlock failed"
