[projects."/home/barts/code/personal/python/wslpy"]
trust_level = "trusted"

[projects."/home/barts/code/work/python/python-package-fr-report"]
trust_level = "trusted"

[projects."/home/barts"]
trust_level = "trusted"

[projects."/home/barts/code/personal/dotfiles/dotfiles-pi"]
trust_level = "trusted"

[projects."/home/barts/code/personal/dotfiles/dotfiles-arch"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4

[plugins."github@openai-curated"]
enabled = true
