#!/usr/bin/env bash

set -eo pipefail

lg "Creating a new rclone configuration for Dropbox non-interactive."
rclone config create --obscure dropbox dropbox config_is_local=false token="$(bw-cli-get password rclone_dropbox)" > /dev/null

lg "Syncing Dropbox. This may take a while."
rclone sync dropbox: ~/dropbox
rclone bisync dropbox: ~/dropbox --resync
