#!/usr/bin/env bash

# Ensure rclone is installed
if ! command -v rclone &>/dev/null; then
    lg "rclone is not installed. Please install it and try again."
    exit 1
else
    lg "rclone is installed. Dropbox will be configured. You will need to authenticate your Dropbox account with the browser."
fi

lg "Creating a new rclone configuration for Dropbox."
rclone config create dropbox dropbox config_is_local false

lg "Reconnecting to Dropbox."
rclone config reconnect dropbox:

lg "Syncing Dropbox. This may take a while."
rclone sync dropbox: ~/dropbox
rclone bisync dropbox: ~/dropbox --resync
