#!/usr/bin/env bash

get_spell(){
    lang=$1
    mkdir ~/.config/nvim/spell --parent
    curl -o ~/.config/nvim/spell/$lang.utf-8.spl http://ftp.vim.org/pub/vim/runtime/spell/$lang.utf-8.spl
}

symlink_config () {

    dotfiles=~/dotfiles/nvim
    directory_config=~/.config/nvim

    mkdir $directory_config -p
    ln $dotfiles/lua $directory_config/lua -sf
    ln $dotfiles/vim $directory_config/vim -sf
    ln $dotfiles/after $directory_config/after -sf
    ln $dotfiles/plugin $directory_config/plugin -sf
    ln $dotfiles/init.lua $directory_config/init.lua -sf
    ln $dotfiles/lazy-lock.json $directory_config/lazy-lock.json -sf
}

make_dict(){
    lang=$1
    storage=$2
    file="$lang.dict"

    echo "Creating aspell dictionary $file at $storage"
    mkdir $storage --parents

    pushd .
    cd $storage
    aspell -d $lang dump master | aspell -l $lang expand > $file
    popd
}

echo "# Vim"
symlink_config 
# make_dict nl "$HOME/.config/nvim/dict"
# make_dict en "$HOME/.config/nvim/dict"
get_spell nl
get_spell en
ln -sf ~/dotfiles/scripts/sorters/sort_variable_length ~/bin/
sudo pacman -S pynvim
