#!/usr/bin/env bash

get_spell() {
    lang=$1
    mkdir ~/.config/nvim/spell --parent
    curl -o ~/.config/nvim/spell/$lang.utf-8.spl http://ftp.vim.org/pub/vim/runtime/spell/$lang.utf-8.spl
}

symlink_config() {

    local directory_config=$1
    dotfiles=~/dotfiles/nvim

    rm "$directory_config" -rf
    mkdir "$directory_config" -p

    # Subdirectories are linked to avoid spell and .luarc.json files to be
    # added to my dotfiles. Also, it works better if lazy-lock.json is a
    # hardlink
    ln $dotfiles/lua "$directory_config" -sf
    ln $dotfiles/vim "$directory_config" -sf
    ln $dotfiles/init.lua "$directory_config"/init.lua -sf
    cp $dotfiles/lazy-lock.json "$directory_config"/lazy-lock.json # cannot be linked

}

echo "# nvim"
symlink_config ~/.config/nvim
get_spell nl
get_spell en
sudo pacman -S python-pynvim --noconfirm
