#!/usr/bin/env bash
set -euo pipefail

this_dir="$(dirname "$(readlink -f "$0")")"
. "$this_dir/regexes.sh"

################################################################################
# Some patterns that can be selected by fzf cannot be accepted by the program
# that opens them. The functions in this file correct that.
################################################################################

################################################################################
# Python errors do not respect the file:line:column convention for a text file.
# This is corrected using sed.
################################################################################
RE="$RE_PYTHON_ERROR|$RE_PYTHON_ERROR_WIN|"
sed_python_error() {
    sed -E "s/$RE/\1:\2:/g"
}

sed_python_error
