#!/usr/bin/env bash

echo "Linking user systemd services"
mkdir -p ~/.config/systemd/user

if running_wsl; then
    ln -sf ~/dotfiles-linux/systemd/user/dropbox.service ~/.config/systemd/user/dropbox.service
    systemctl --user enable dropbox.service
    systemctl --user start dropbox.service
fi
