#!/usr/bin/env bash

enable_autologin() {
    unit="$HOME/dotfiles-linux/systemd/getty@tty1.service.d/"

    echo "Enabling autologin for user barts on tty1 by copying '$unit' to '/etc/systemd/system/'"
    sudo cp -rf "$unit" /etc/systemd/system/
    sudo systemctl enable getty@tty1.service
    sudo systemctl start getty@tty1.service
}

enable_autologin
sudo systemctl daemon-reload
