#!/usr/bin/env zsh

set -eo pipefail

this_dir=$(dirname "$(realpath "${BASH_SOURCE:-$0}")")

source "$this_dir/helpers.bash"

source="$this_dir/davmail.properties"
directory_config=~/.config/davmail

copy_config "$source" "$directory_config"
