#!/bin/bash

. ~/dotfiles-linux/dependencies/helpers.sh

dir=~/dotfiles-linux/dependencies

echo "# Dependencies"
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y "$(cat "$dir/apt.txt")"
install-tmux-session
install-fzf-help
