#!/bin/bash

. ~/dotfiles-linux/dependencies/helpers.sh
. ~/dotfiles-linux/dependencies/deps.sh

dir=~/dotfiles-linux/dependencies

echo "# Dependencies"
sudo pacman -Syu --noconfirm
sudo pacman -S --needed base-devel --noconfirm
install_yay
sudo pacman -S --noconfirm - < $dir/pacman.txt
yay -S --noconfirm - < $dir/aur.txt
install_node_js
link_scripts_to_bin
dropbox-cli autostart y
install_python_packages $dir/pip.txt

if ! running_wsl; then
    sudo pacman -S --noconfirm - < $dir/pacman_wayland.txt
fi
