#!/usr/bin/env bash
set -euo pipefail

this_dir="$(dirname "$(readlink -f "$0")")"
. "$this_dir/regexes.bash"

################################################################################
# Combine the regexes into 1. All patterns that match will also be send to fzf
# for selection.
################################################################################
RE="($RE_PYTEST_ERROR)|($RE_CLANG_ERROR)|($RE_PYTHON_ERROR)"
grep -noiE "$RE"
