#!/bin/bash

dir=~/dotfiles-linux/arch

. $dir/helpers.sh

lg "# Installing dependencies pacman"
sudo pacman -Syu --noconfirm
sudo pacman -S --needed base-devel --noconfirm
sudo pacman -S --noconfirm - <$dir/pacman.txt

lg "# Installing dependencies AUR"
install_yay /tmp/yay
yay -S --noconfirm - <$dir/aur.txt

lg "# Installing node.js"
install_node_js

lg "# Installing python packages"
install_python_packages $dir/pip.txt
