#!/bin/bash

dir=~/dotfiles-linux/arch

. $dir/helpers.sh

lg "# Updating pacman"
sudo pacman -Syu --noconfirm
lg "# Installing base dependencies pacman"
sudo pacman -S --needed base-devel --noconfirm
lg "# Installing user dependencies pacman"
sudo cat "$dir/pacman.txt" | sudo pacman -S --noconfirm -

lg "# Installing dependencies AUR"
install_yay /tmp/yay
yay -S --noconfirm - <$dir/aur.txt

lg "# Installing node.js"
install_node_js

lg "# Installing python packages"
install_python_packages $dir/pip.txt
