#!/usr/bin/bash

# Choose firefox when running wsl, otherwise choose feh.
if running_wsl; then
    [ ! -z "$1" ] && win_path=$(wslpath -w $1)
    /usr/bin/firefox $win_path
else
    /usr/bin/feh $@
fi
