#!/usr/bin/env bash

account=${MICROSOFT_ACCOUNT:-}
[[ -z $account ]] && {
    echo "MICROSOFT_ACCOUNT not set"
    exit 1
}
username=$(bw-cli-get username $account)

mutt_oauth2 --verbose --authorize "$HOME/.config/neomutt/$username.tokens"
