#!/usr/bin/env bash

set -eo pipefail

directory="$HOME/.config/neomutt"
cache="$HOME/.cache/neomutt"

rm -rf "$directory" || true
rm -rf "$cache" || true

mkdir -p "$directory"
ln -sf "$HOME"/dotfiles-arch/mutt/muttrc "$directory"/muttrc

ln -sf "$HOME"/dotfiles-arch/mutt/mutt_oauth2 "$HOME"/dotfiles-arch/bin/mutt_oauth2

mkdir -p "$HOME"/.local/share/mail/INBOX
mkdir -p "$cache"
touch "$cache"/header_cache
