#!/bin/bash

echo "# Neomutt"
directory="$HOME/.config/neomutt"
cache="$HOME/.cache/neomutt"

mkdir -p $directory
ln -sf $HOME/dotfiles-linux/mutt/muttrc $directory/muttrc

mkdir -p $HOME/.local/share/mail/INBOX
mkdir -p $cache
touch $cache/header_cache

echo "# Downloading emails"
mbsync -a
notmuch new
