#!/bin/bash

dir=~/dotfiles-linux/apt

echo "Installing apt dependencies"
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install -y "$(cat "$dir/apt.txt")"
install-tmux-session
install-fzf-help
