#!/usr/bin/env bash

set -eo pipefail

dir=~/dotfiles-linux/apt

lg "Installing apt dependencies"
sudo apt update -y
sudo apt upgrade -y
cat $dir/apt.txt | xargs sudo apt install -y

# Install latest Neovim (0.11+) from official release tarball (Debian/RPi)
TMP=$(mktemp -d)
curl -L https://github.com/neovim/neovim/releases/latest/download/nvim-linux-arm64.tar.gz -o "$TMP/nvim.tar.gz"
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf "$TMP/nvim.tar.gz"
sudo mv /opt/nvim-linux-arm64 /opt/nvim
sudo ln -sf /opt/nvim/bin/nvim /usr/local/bin/nvim

$dir/build_rbw

lg "Creating fd symlink"
mkdir -p ~/.local/bin
ln -s "$(command -v fdfind)" ~/.local/bin/fd
