#!/usr/bin/env bash

get_usage() {
    cat <<EOF
Usage: enable-autologin <ttyN>
Where <ttyN> is the number of the tty you want to enable autologin on.
For example, if you want to enable autologin on tty1, you would run:
    enable-autologin 1
EOF
}

write_file() {
    cat <<EOF >$1
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin $USER %I \$TERM
EOF
}

enable_autologin() {
    # check if positional arguments are empty
    if [ -z "$1" ]; then
        get_usage
        exit 1
    fi

    ttyN=$1
    unit="/etc/systemd/system/getty@tty$ttyN.service.d"
    tmp="/tmp/autologin.conf"
    file="$unit/autologin.conf"

    echo "Enabling autologin for user $USER on tty$ttyN by creating the following file: $file"
    sudo mkdir -p $unit

    write_file $tmp
    sudo cp -u $tmp $file
    rm $tmp

    sudo systemctl enable getty@tty$ttyN.service
    sudo systemctl start getty@tty$ttyN.service
    sudo systemctl daemon-reload
}

enable_autologin $@
