#!/bin/bash
# Use fzf to select 1 of the rbw entries, which we call `id`. Next, feed this
# `id` to `rbw get` and send the stdout to the clipboard.

rbw_to_clipboard(){
    id=$(rbw list | fzf)

    # FIXME: the wl-copy breaks.
    rbw_get $cmd $id | wl-copy
}

if [[ $# -eq 1 ]]; then
  cmd=$1
elif [[  $# -gt 1  ]]; then
  echo "Error: Only one argument allowed."
  exit 1
else
  cmd=password
fi

rbw unlocked && rbw_to_clipboard || echo
