#!/usr/bin/env bash

usage="Usage: setup-ftpu.sh [options] <drive>

Configure a raspberry pi to run an sftp server to download/upload files to a 
hard drive. The hard drive is mounted under /my-fdd-drive and is mapped to the
user ftpu. The user ftpu has a home directory /home/ftpu/data which is mapped
to the hard drive. The user ftpu can be used to access the hard drive from
anywhere within the local network.

First, make sure that the hard drive is unmounted, you can check this by
running:

    sudo df --human-readable --print-type

And then unmount the drive by running:

    sudo umount --verbose /current_mount_point

Run the following to locate the drive if you did not already know it (For me,
it was \`/dev/sda1\`):

    sudo fdisk -l

Provide the drive to the script as an argument. For example:

    setup-ftpu /dev/sda1

The script was based on the following article: 
- medium.com/kunalrdeshmukh/ftp-erver-with-raspberry-pi-and-hdd-3c10ce95f2d4

Arguments:
  <drive>         The drive to mount, e.g. /dev/sda1.

Options:
  -h, --help  Show this message and exit."

final_message="Done. You can try any sftp client to connect to raspberry pi.
Use ftp user as : ftpu
- IP : IP address of raspberry pi.
- Password : Password of ftpu user.
This will allow you to access your Portable HDD from anywhere within your
local network (most likely your home)."

running_raspberry() {
    if [ -f /proc/device-tree/model ]; then
        grep -q "Raspberry Pi" /proc/device-tree/model
        if [ $? -eq 0 ]; then
            return 0
        else
            return 1
        fi
    else
        return 1
    fi
}

assert_raspberry() {
    if ! running_raspberry; then
        echo "This script is meant to be run on a Raspberry Pi."
        exit 1
    fi

}

perpare() {
    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo apt-get -y dist-upgrade
}

mount_drive() {
    cd /
    sudo mkdir my-fdd-drive
    sudo mount "$1" "$2"
    sudo chmod 775 "$2"
}

# Add a line to the end of /etc/fstab if it does not exist
extend_fstab() {
    line="$1"
    if ! grep -q "$line" /etc/fstab; then
        echo "$line" | sudo tee -a /etc/fstab
    fi
}

add_ftpu_user() {
    sudo adduser ftpu
    sudo mkdir /home/ftpu/data
    sudo chown ftpu:ftpu /home/ftpu/data
}

drive=""
mount_point="/my-fdd-drive"
while [ "$1" != "" ]; do
    case $1 in
        -h | --help)
            echo "$usage"
            exit
            ;;
        *)
            if [ -z "$drive" ]; then
                drive="$1"
            else
                echo "Error: unknown argument"
                echo "$usage"
                exit 1
            fi
            ;;
    esac
    shift
done

assert_raspberry
perpare
mount_drive "$drive" "$mount_point"
extend_fstab "$drive $mount_point ntfs defaults 0 0"
add_ftpu_user
extend_fstab "$mount_point /home/ftpu/data none bind 0 0"
sudo raspi-config
echo "$final_message"
