#!/usr/bin/env bash

set -eo pipefail

source ~/.zshenv

# Set user shell to zsh
sudo chsh -s /usr/bin/zsh "$(whoami)"

# Set root shell to zsh
sudo chsh -s /usr/bin/zsh root

# Ensure history file exists
touch "$HISTFILE"
