#!/usr/bin/env bash

set -euo pipefail
this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$this_dir/helpers"

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root"
    exit 1
elif ! is_mutable /etc/NetworkManager/NetworkManager.conf "$(readlink -f /etc/resolv.conf)" /etc/sudoers; then
    lg "The DNS settings are already locked. Exiting."
    exit 1
fi

lg "Only the root user can use the chattr command from now on"
update_sudoers

echo "Locking DNS settings"
chattr +i /etc/NetworkManager/NetworkManager.conf
chattr +i "$(readlink -f /etc/resolv.conf)"
chattr +i /etc/sudoers
