#!/usr/bin/env bash
set -euo pipefail

this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo cp -u "$this_dir"/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf

sudo systemctl restart NetworkManager
sudo systemctl restart systemd-resolved
sudo systemd-resolve --flush-caches

sleep 5
echo "Setting DNS configuration"
nmcli device show | grep IP4
