#!/usr/bin/env bash
set -euo pipefail

this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sudo mkdir -p /etc/NetworkManager/conf.d
sudo cp -u "$this_dir"/dns.conf /etc/NetworkManager/conf.d/dns.conf
# sudo cp -u "$this_dir"/dns-servers.conf /etc/NetworkManager/conf.d/dns-servers.conf

sudo systemctl restart systemd-resolved
sudo systemd-resolve --flush-caches

sudo systemctl restart NetworkManager

sleep 5
echo "Setting DNS configuration"
nmcli device show | grep IP4

#TODO: read https://wiki.archlinux.org/title/systemd-resolved
