#!/usr/bin/env bash

#######################################
# Link wakatime config
#######################################
link_config() {
    source="$HOME/dotfiles/waka/.wakatime.cfg"
    echo "Wakatime: link '$source' to '$HOME/.wakatime.cfg'"
    ln -sf "$source" "$HOME/.wakatime.cfg" || echo "Wakatime: linking failed"
    echo "Done"
}

link_config
