#!/usr/bin/env bash

#######################################
# Link wakatime config
#######################################
link_config() {

    if running_wsl; then
        source="$WH/Dropbox/Config/.wakatime.cfg"
    else
        source="$HOME/Dropbox/Config/.wakatime.cfg"
    fi

    echo "Wakatime: link '$source' to '$HOME/.wakatime.cfg'"
    ln -sf "$source" "$HOME/.wakatime.cfg" || echo "Wakatime: linking failed"
    echo "Done"
}

link_config
