#!/bin/bash

. ~/dotfiles-linux/pacman/helpers.sh

dir=~/dotfiles-linux/pacman

echo "# Installing dependencies pacman"
sudo pacman -Syu --noconfirm
sudo pacman -S --needed base-devel --noconfirm
install_yay
sudo pacman -S --noconfirm - < $dir/pacman.txt
yay -S --noconfirm - < $dir/aur.txt
install_node_js
install_python_packages $dir/pip.txt
install-tmux-session
install_fzf_help
cat $dir/pip.txt | xargs -n 1 pipx install
