#!/usr/bin/env bash

set -euo pipefail

this_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
tmp_dir="/tmp/blackweb"

enable_squid() {
    if ! sudo systemctl is-enabled --quiet squid; then
        echo "Squid is not enabled. Enabling it..." >&2
        sudo systemctl enable squid
    fi
}

stop_squid() {
    if sudo systemctl is-active --quiet squid; then
        echo "Squid is running. Stopping it..." >&2
        sudo systemctl stop squid
    fi
}

copy_override() {
    echo "Copying override.conf..." >&2
    sudo mkdir -p /etc/systemd/system/squid.service.d
    sudo cp -f "$this_dir/override.conf" "/etc/systemd/system/squid.service.d/override.conf"
    sudo systemctl daemon-reload
}

copy_blackweb() {
    rm -rf "$tmp_dir" || true
    "$this_dir"/download_blackweb "$tmp_dir"
    sudo cp -f "$tmp_dir/blackweb.txt" "/etc/squid/blackweb.txt"
    sudo chown proxy:proxy /etc/squid/blackweb.txt
    sudo chmod 644 /etc/squid/blackweb.txt
}

enable_squid
stop_squid
copy_override
copy_blackweb
sudo cp -f "$this_dir/squid.conf" "/etc/squid/squid.conf"
"$this_dir"/make_proxy_transparent -p 3128 -i wlp1s0

# TODO: try https://dev.to/suntong/squid-proxy-and-ssl-interception-1oa4

echo "Restarting Squid..." >&2
sudo squid -z
sudo systemctl restart squid
