#!/usr/bin/env bash

set -euo pipefail

this_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

usage="Usage: make_proxy_transparent

Make the proxy transparent by redirecting the traffic from <interface> at port
80 (the default HTTP port) to the proxy port (default 3128 of Squid). Requires
iptables and Squid to be installed.

options:
    -p, --port      The port of the proxy. Default is 3128 (Squid).
    -i, --interface The interface to redirect the traffic from. Default is eth0.
    -s, --save      File to save the iptables rules to. Default is /etc/iptables/iptables.rules.
    -h, --help      Show this help message."

while [[ $# -gt 0 ]]; do
    case "$1" in
    -p | --port)
        port="$2"
        shift
        shift
        ;;
    -i | --interface)
        interface="$2"
        shift
        shift
        ;;
    -s | --save)
        save="$2"
        shift
        ;;
    -h | --help)
        echo "$usage"
        exit 0
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

port=${port:-3129}
interface=${interface:-eth0}
save=${save:-/etc/iptables/iptables.rules}

reset() {
    sudo iptables -t nat -F
    sudo iptables -t nat -X
    sudo iptables -F
    sudo iptables -X
}

# Enable transparent proxy
redirect() {
    sudo iptables -t nat -A PREROUTING -i "$interface" -p tcp --dport 80 -j REDIRECT --to-ports "$port"
    sudo iptables -t nat -A PREROUTING -i "$interface" -p tcp --dport 443 -j REDIRECT --to-ports "$port"
}

save() {
    sudo iptables-save | sudo tee "$save"
}

reset
redirect
save
