#!/usr/bin/env bash

set -euo pipefail

usage="Usage: make_proxy_transparent

Make the proxy transparent by redirecting the traffic from port 80 (the default
HTTP port) to the proxy port (default 3128 of Squid). Requires iptables and
Squid to be installed.

options:
    -p, --port      The port of the proxy. Default is 3128 (Squid).
    -s, --save      File to save the iptables rules to. Default is /etc/iptables/iptables.rules.
    -h, --help      Show this help message."

while [[ $# -gt 0 ]]; do
    case "$1" in
    -p | --port)
        port="$2"
        shift
        shift
        ;;
    -s | --save)
        save="$2"
        shift
        ;;
    -h | --help)
        echo "$usage"
        exit 0
        ;;
    *)
        echo "Unknown option: $1"
        exit 1
        ;;
    esac
done

port=${port:-3128}
save=${save:-/etc/iptables/iptables.rules}

reset() {
    sudo iptables -t nat -F
    sudo iptables -t nat -X
}

enable_forwarding() {
    echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
    sudo sysctl -w net.ipv4.ip_forward=1
    echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/99-sysctl.conf
}

redirect() {
    sudo iptables -t nat -A OUTPUT \
        -p tcp --dport 80 \
        -m owner \! --uid-owner proxy \
        -j REDIRECT --to-port "$port"
}

save() {
    sudo iptables-save | sudo tee "$save"
}

reset
enable_forwarding
redirect
save
sudo systemctl enable iptables
sudo systemctl restart iptables
