#!/usr/bin/env bash

set -eo pipefail

lg "Enable systemd for WSL"
sudo cp ~/dotfiles-linux/wsl/wsl.conf /etc/wsl.conf

lg "Install wslpy"
tmpdir=$(mktemp -d) && git clone https://github.com/BartSte/wslpy "$tmpdir/wslpy" && (cd "$tmpdir/wslpy" && ./install.sh) && rm -rf "$tmpdir"
