#!/usr/bin/env bash

set -eo pipefail

# ensure lg exists for non-interactive shells
if ! command -v lg &>/dev/null; then
  lg() { echo "$@"; }
fi

# check if safe-rm is installed
if ! command -v safe-rm &>/dev/null; then
    lg "safe-rm could not be found (skipping)"
    exit 0
else
    lg "Copying config file to /etc/safe-rm.conf"
    sudo cp ~/dotfiles-linux/safe-rm/safe-rm.conf /etc/safe-rm.conf
fi
