#!/bin/env bash

set -eo pipefail

usage="main [-h, --help, --dry-run]

Runs the 'auth' scripts in the '~/dotfiles-linux' directory.

Options:
    --dry-run     Dry run mode.
    -h, --help    Show this help message and exit."

DIR=~/dotfiles-linux
DRY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
    --dry-run)
        DRY=true
        shift
        ;;
    -h | --help)
        echo "$usage"
        exit 0
        ;;
    *)
        lg "Unknown option: $1"
        exit 1
        ;;
    esac
done

main() {
    lg "Installing BartSte/dotfiles-linux repository"
    . $DIR/home/.zshenv
    source ~/.dotfiles_config.sh

    lg "All the auth files are executed. User interaction is required."
    execute
}

execute() {
    local front=(bitwarden git vdirsyncer)
    local -A seen

    mapfile -t all_dirs < <(find "$DIR" -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | sort)

    for module in "${front[@]}"; do
        if [[ -x "$DIR/$module/auth" ]]; then
            seen["$module"]=1
            if $DRY; then
                lg "(dry) $DIR/$module/auth"
            else
                lg "Auth: $module"
                "$DIR/$module/auth"
            fi
        fi
    done

    for module in "${all_dirs[@]}"; do
        [[ -n ${seen[$module]+x} ]] && continue
        if [[ -x "$DIR/$module/auth" ]]; then
            if $DRY; then
                lg "(dry) $DIR/$module/auth"
            else
                lg "Auth: $module"
                "$DIR/$module/auth"
            fi
        fi
    done
}

main
