#!/bin/env bash

set -eo pipefail

function clone() {
    git clone --bare "$1" "$2"
}

function checkout() {
    git --work-tree="$HOME" --git-dir="$1" checkout -f
}

github="https://github.com/BartSte"

base="$github/dotfiles.git"
base_dir="$HOME/dotfiles.git"

lin="$github/dotfiles-linux.git"
lin_dir="$HOME/dotfiles-linux.git"

echo "# Installing git" >&2
sudo pacman -S git --noconfirm || sudo apt install git -y

echo "# Clone BartSte/dotfiles.git as a bare repository" >&2
clone $base "$base_dir"
checkout "$base_dir"

echo "# Clone BartSte/dotfiles-linux.git as a bare repository" >&2
clone $lin "$lin_dir"
checkout "$lin_dir"

echo "# Setup the environment variables" >&2
source "$HOME"/dotfiles-linux/home/.zshenv

touch "$HOME"/.dotfiles_config.sh
~/.dotfiles_config.sh <<EOF
export BWEMAIL=
export MICROSOFT_ACCOUNT=
EOF

echo "
Please complete the file '$HOME/.dotfiles_config.sh' by setting the following
environment variables:

- BWEMAIL: the email use for bitwarden password manager. This is always you
    personal email since work paswords are also stored here. You have 3 with the
    following emails:
    - work -> your work email
    - personal -> your personal email
    - RpiBot -> the sudo...@gmail.com email used by the RpiBot.

- MICROSOFT_ACCOUNT: the bitwarden key (MicrosoftPersonal or MicrosoftWork)
    that holds the credentials to your microsft account. The microsft account
    is used to configure neomutt and isync."
