#!/bin/env bash

set -eo pipefail

function clone() {
    git clone --bare "$1" "$2"
}

function checkout() {
    git --work-tree="$HOME" --git-dir="$1" checkout -f
}

github="https://github.com/BartSte"

base="$github/dotfiles.git"
base_dir="$HOME/dotfiles.git"

lin="$github/dotfiles-linux.git"
lin_dir="$HOME/dotfiles-linux.git"

echo "# Installing git" >&2
sudo pacman -S git --noconfirm || sudo apt install git -y

echo "# Clone BartSte/dotfiles.git as a bare repository" >&2
clone $base "$base_dir"
checkout "$base_dir"

echo "# Clone BartSte/dotfiles-linux.git as a bare repository" >&2
clone $lin "$lin_dir"
checkout "$lin_dir"

echo "Setup the environment variables" >&2
source "$HOME"/dotfiles-linux/home/.zshrc

touch "$HOME"/.dotfiles_config.sh
echo "export MICROSOFT_ACCOUNT=" >>"$HOME"/.dotfiles_config.sh >&2

cat <<EOF
Please complete the file '$HOME/.dotfiles_config.sh' by setting the one of the 
following two microsft accounts: 
 - export MICROSOFT_ACCOUNT=MicrosoftPersonal 
 - export MICROSOFT_ACCOUNT=MicrosoftWork
One of these accounts is used to configure the mail accounts for neomutt and
isync, using bitwarden to retrieve the passwords.
EOF
