#!/bin/env bash

usage() {
    cat <<EOF
Usage: main [OPTION]...

This script resides in a directory where each subdirectory is a module. The 
modules that contain a file called `main` will be executed by running the `main`
script.

In general, the order does not matter. However, the directories listed in the 
`execute_first` array need to be executed first, in the order they are listed.

options:
    -h, --help      Show this help message.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "Installing BartSte/dotfiles-linux repository"

source ~/.dotfiles_config.sh

dir=~/dotfiles-linux
execute_first=(
    "dependencies"
    "systemd"
    "bitwarden"
    "home"
)

# Execute the modules in the `execute_first` array.
for module in "${execute_first[@]}"; do
    echo "Executing module: $module"
    $dir/$module/main
done

# Execute all other modules. Do not execute the modules in the `execute_first`.
for module in $(ls $dir); do
    if [[ " ${execute_first[@]} " =~ " ${module} " ]]; then
        echo "Skipping module: $module. It was already executed."
    elif [[ -f "$dir/$module/main" ]]; then
        echo "Executing module: $module"
        $dir/$module/main
    fi
done
    
echo "Done"
