#!/usr/bin/env bash

get_usage() {
    cat <<EOF
Usage: $0 [options]

This script is used to grep pytest error file:line:error from stdin. Note that
this script is compatible with Windows paths (\) and Unix paths (/).

options:
    -h, --help: show this help message and exit
EOF
}

if [[ $1 == '-h' || $1 == '--help' ]]; then
    get_usage
    exit 0
fi

RE_PYTEST_ERROR="^[a-zA-Z0-9\\\/\_]*\.py:[0-9]+:"
grep -Eoi $RE_PYTEST_ERROR
