#!/usr/bin/env bash

is_auth=$(gh auth status | grep "Logged in to github.com")
if [[ -n $is_auth ]]; then
    echo "Already authenticated"
else
    gh auth login
fi

has_copilot=$(gh extension list | grep "gh-copilot")
if [[ -n $has_copilot ]]; then
    echo "gh-copilot already installed, upgrading..."
    gh extension upgrade gh-copilot
else
    gh extension install github/gh-copilot
fi
