#!/usr/bin/env bash

set -eo pipefail

source="$HOME/dotfiles-arch/isync/.mbsyncrc_$MICROSOFT_ACCOUNT"
destination="$HOME/.mbsyncrc"

[ -f "$source" ] || {
    lg "Source: $source does not exist!"
    exit
}

lg "Remove $destination"
rm "$destination" || true

lg "Symlink $source to $destination"
ln --symbolic "$source" "$destination"
