#!/bin/bash
#
source="$HOME/dotfiles-linux/isync/.mbsyncrc_$MICROSOFT_ACCOUNT"
destination="$HOME/.mbsyncrc"

[ -f $source ] || { lg "Source: $source does not exist!"; exit; }

lg "Remove $destination"
rm $destination

lg "Symlink $source to $destination"
ln --symbolic $source $destination
