#!/bin/bash

MS_EMAIL=$(rbw_get username "$MICROSOFT_ACCOUNT")
MS_REALNAME=$(rbw_get name "$MICROSOFT_ACCOUNT")

export MS_EMAIL
export MS_REALNAME

script="Key-Type: 1
Key-Length: 2048
Subkey-Type: 1
Subkey-Length: 2048
Name-Real: $MS_REALNAME
Name-Email: $MS_EMAIL
Expire-Date: 0"

lg "$script" > /tmp/gen-key-script
gpg --batch --gen-key /tmp/gen-key-script
rm /tmp/gen-key-script

unset MS_EMAIL
unset MS_REALNAME

mkdir -p ~/.gnupg/
ln -sf ~/dotfiles-linux/gpg/gpg-agent.conf ~/.gnupg/gpg-agent.conf
