name: Test
on: [push]

concurrency:
  group: test-arch-linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-arch-linux:
    runs-on: ubuntu-latest
    container: archlinux:latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup barts user
        run: |
          useradd -m barts -s /bin/bash
          echo 'barts ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

      - name: Prepare repository
        run: |
          mkdir -p /home/barts/dotfiles-linux
          cp -r "$GITHUB_WORKSPACE"/. /home/barts/dotfiles-linux/
          chown -R barts:barts /home/barts/dotfiles-linux

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: pacman-packages-${{ hashFiles('/home/barts/dotfiles-linux/arch/pacman.txt') }}

      - name: Initialize
        run: |
          pacman -Syu --noconfirm git sudo base-devel
          sudo -u barts bash -c '
            cd /home/barts/dotfiles-linux
            bash initialize
            echo "export MICROSOFT_ACCOUNT=MicrosoftPersonal" > "$HOME/.dotfiles_config.sh"
          '

      - name: Cache yay packages
        uses: actions/cache@v4
        with:
          path: /home/barts/.cache/yay
          key: yay-packages-${{ hashFiles('/home/barts/dotfiles-linux/arch/aur.txt') }}

      - name: Main
        run: |
          sudo -u barts bash -c '
            export CI=true
            ~/dotfiles-linux/main
          '
