name: Test
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-changes:
    name: Check for changes
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
    steps:
      - name: Check code changes
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = context.ref.replace('refs/heads/', '');
            const currentSha = context.sha;
            const workflowRuns = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: context.workflow,
              branch,
              status: 'success',
              per_page: 1
            });
            if (workflowRuns.data.total_count === 0) {
              core.setOutput('has_changes', 'true');
              return;
            }
            const lastRunSha = workflowRuns.data.workflow_runs[0].head_sha;
            const hasChanges = lastRunSha !== currentSha;
            core.setOutput('has_changes', hasChanges.toString());

  test-arch-linux:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'true' }}
    concurrency:
      group: test-arch-linux-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    container: archlinux:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: pacman -Sy --noconfirm git sudo base-devel

      - name: Setup barts user
        run: |
          useradd -m barts -s /bin/bash
          echo 'barts ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

      - name: Initialize
        run: |
          sudo -u barts bash -c '
            cd /home/barts
            curl -O https://raw.githubusercontent.com/BartSte/dotfiles-linux/master/dotfiles-linux/initialize
            bash ./initialize
            rm ./initialize
            echo "export MICROSOFT_ACCOUNT=MicrosoftPersonal" > "$HOME/.dotfiles_config.sh"
          '

      - name: Cache pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: pacman-packages-${{ hashFiles('/home/barts/dotfiles-linux/arch/pacman.txt') }}

      - name: Cache yay packages
        uses: actions/cache@v4
        with:
          path: /home/barts/.cache/yay
          key: yay-packages-${{ hashFiles('/home/barts/dotfiles-linux/arch/aur.txt') }}

      - name: Set yay cache ownership
        run: chown -R barts:barts /home/barts/.cache

      - name: Main
        run: |
          sudo -u barts bash -c '
            export CI=true
            ~/dotfiles-linux/main
          '
