name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Deps
        run: pacman -Sy --noconfirm git sudo

      - name: Initialize
        run: |
          curl -O https://raw.githubusercontent.com/BartSte/dotfiles-linux/master/dotfiles-linux/initialize && bash ./initialize; rm ./initialize
          echo "export MICROSOFT_ACCOUNT=MicrosoftPersonal" > "$HOME/.dotfiles_config.sh"

      - name: Main
        run: |
          ~/dotfiles-linux/main
