name: Test
on: [push]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Deps
        run: pacman -Sy --noconfirm git sudo

      - name: Setup barts user
        run: |
          useradd -m barts
          echo 'barts ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

      - name: Initialize
        run: |
          sudo -u barts bash -c '
            cd /home/barts
            curl -O https://raw.githubusercontent.com/BartSte/dotfiles-linux/master/dotfiles-linux/initialize
            bash ./initialize
            rm ./initialize
            echo "export MICROSOFT_ACCOUNT=MicrosoftPersonal" > "$HOME/.dotfiles_config.sh"
          '

      - name: Main
        run: sudo -u barts bash -c '~/dotfiles-linux/main'
